package com.pokemon.demo.ROLES;


public enum MonsterType {
    NORMAL, FIRE, WATER, ELECTRIC, GRASS, ICE,
    FIGHTING, POISON, GROUND, FLYING, PSYCHIC,
    BUG, ROCK, GHOST, DARK, DRAGON, STEEL, FAIRY
}
